version: '3.9'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - api
    networks:
      - my-network
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # ports:
    #   - '3000:3000'
    depends_on:
      - mongo
    networks:
      - my-network
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:

volumes:
  mongo-data:
